apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 714885846333.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 714885846333.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 4b56047a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
